name: test_coverage_reporter
description: A starting point for Dart libraries or applications.
version: 1.1.4
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.5.0
  test: any

dev_dependencies:
  lints: ^3.0.0

bin:
  # Name of your executable file (without the .test_coverage_reporter.dart extension)
  test_coverage_reporter: # This should match your file name
